config/routes.rb
Rails.application.routes.draw do
  
  root 'users#register'

  get 'lands/rivendell' => 'lands#rivendell'

  post 'sessions/create' => 'sessions#create'

  get 'sessions/destroy' => 'sessions#destroy'

  post 'users/create' => 'users#create'

  get 'register' => 'users#register'

  get 'users/login'

  post 'auth/fitbit'

  get 'auth/fitbit/callback' => 'fitbit_auth#get_response'

  get 'dashboards/index' 

 

end

app/models/user.rb
class User < ActiveRecord::Base
	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

    validates :email, presence:true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
    validates :password, confirmation: true, presence:true, length: { minimum: 6 }
    

 def self.authenticate(email)
    user = User.find_by_email(email)
    if user 
    # && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
	end

	def get_api
		$fitbit_uri = ""
	end
end

app/controllers/fitbit_auth_controller.rb
class FitbitAuthController < ApplicationController
	
  def get_response
    # Callback from Fitbit Oauth

    # Oauth Access Credentials
    oauth_token = params[:oauth_token]
    oauth_verifier = params[:oauth_verifier]

    # User Information and User Access Credentials
    @fitbit_data  = request.env['omniauth.auth']

    user = User.find(session[:user_id])
    user.update(full_name:@fitbit_data["info"]["display_name"], fitbit_uid:@fitbit_data["uid"], fitbit_token:@fitbit_data["credentials"]["token"], fitbit_secret:@fitbit_data["credentials"]["secret"])
    # Get User Activity Information
    # activities = get_user_activities(fitbit_data)
    # user = get_user_info(fitbit_data)
    total_distance = get_user_distance(@fitbit_data)
    @distance = total_distance
    puts "HERE IS THE DISTANCE:", @distance
    # puts "HERE IS MOAR:", @distance.activities-tracker-distance


    @fitbit_data[:token] = oauth_token = params[:oauth_token]
    @fitbit_data[:verifier] = oauth_token = params[:oauth_verifier]
    
    # session[:distance] = @distance
    # render json:activities
    # render json:user
    # render json:fitbit_data
    # render json:@distance
    # redirect_to '/dashboards/index'

    # session[:fitbit] = @fitbit_data
    # render json:activities
    # render json:user
    # render json:@fitbit_data
    # render json:@fitbit_data
    render '/dashboards/index'
  end

private
  def get_user_activities(fitbit_data)
    fitbit_user_id = fitbit_data["uid"]
    user_secret = fitbit_data["credentials"]["secret"]
    user_token = fitbit_data["credentials"]["token"]

    # Store this information in you user model for
    # logins in the future.
    client = Fitgem::Client.new({
      consumer_key: ENV['FITBIT_CLIENT_KEY'],
      consumer_secret: ENV['FITBIT_CLIENT_SECRET'],
      token: user_token,
      secret: user_secret,
      user_id: fitbit_user_id,
    })

    # Reconnects existing user using the information above
    access_token = client.reconnect(user_token, user_secret)

    # client.activities_on_date('2015-03-25') <- Specific Date
    client.activities_on_date('today')
    # client.activity_statistics
  end

  def get_user_info(fitbit_data)
    fitbit_user_id = fitbit_data["uid"]
    user_secret = fitbit_data["credentials"]["secret"]
    user_token = fitbit_data["credentials"]["token"]

    # Store this information in you user model for
    # logins in the future.
    client = Fitgem::Client.new({
      consumer_key: ENV['FITBIT_CLIENT_KEY'],
      consumer_secret: ENV['FITBIT_CLIENT_SECRET'],
      token: user_token,
      secret: user_secret,
      user_id: fitbit_user_id,
    })

    # Reconnects existing user using the information above
    access_token = client.reconnect(user_token, user_secret)

    # get user information with fitgem

    client.user_info
  end

  def get_user_distance(fitbit_data)
    fitbit_user_id = fitbit_data["uid"]
    user_secret = fitbit_data["credentials"]["secret"]
    user_token = fitbit_data["credentials"]["token"]

    # Store this information in you user model for
    # logins in the future.
    client = Fitgem::Client.new({
      consumer_key: ENV['FITBIT_CLIENT_KEY'],
      consumer_secret: ENV['FITBIT_CLIENT_SECRET'],
      token: user_token,
      secret: user_secret,
      user_id: fitbit_user_id,
    })

    # Reconnects existing user using the information above
    access_token = client.reconnect(user_token, user_secret)

    # get user information with fitgem

    client.data_by_time_range('/activities/tracker/distance',{:base_date => '2015-10-21', :end_date => 'today'})
  end
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
	def Rivendell
		puts session[:user_id]
		#@friend_achievements =
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	puts 'hello we are inc reat sreasdjakdn'
  	user = User.find_by email: params[:user][:email]
  	puts user.id

    if user
  	  if user.fitbit_token

  	    session[:user_id] = user.id
        @fitbit_data = User.find(session[:user_id])
        total_distance = get_user_distance(@fitbit_data)
        @distance = total_distance
        # render json:@distance
        # puts @distance
        flash[:notice] = "Logged in!"
  	    render "/dashboards/index"

  	  else
  	    redirect_to "/auth/fitbit"
  	  end
    else 
      flash[:error] = "Invalid email or password"
      redirect_to "/user/login"
    end
  end

  def destroy
  session[:user_id] = nil
  flash[:notice] = "Logged out!"
  redirect_to root_url 
end


  private 

def get_user_distance(fitbit_data)
    fitbit_user_id = fitbit_data["fitbit_uid"]
    user_secret = fitbit_data["fitbit_secret"]
    user_token = fitbit_data["fitbit_token"]

    # Store this information in you user model for
    # logins in the future.
    client = Fitgem::Client.new({
      consumer_key: ENV['FITBIT_CLIENT_KEY'],
      consumer_secret: ENV['FITBIT_CLIENT_SECRET'],
      token: user_token,
      secret: user_secret,
      user_id: fitbit_user_id,
    })

    # Reconnects existing user using the information above
    access_token = client.reconnect(user_token, user_secret)

    # get user information with fitgem

        ##get date they started their journey
        # start_date = fitbit_data['created_at']

    client = [
      client.data_by_time_range('/activities/tracker/steps',{:base_date => '2015-10-21', :end_date => 'today'}),
      client.data_by_time_range('/activities/tracker/distance',{:base_date => '2015-10-21', :end_date => 'today'}),
      client.data_by_time_range('/activities/tracker/elevation',{:base_date => '2015-10-21', :end_date => 'today'}),
      client.data_by_time_range('/activities/tracker/calories',{:base_date => '2015-10-21', :end_date => 'today'}),
      client.data_by_time_range('/sleep/minutesAsleep',{:base_date => '2015-10-21', :end_date => 'today'})
    ]

    client

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
	
  puts "users controller"
  def create
  	@user = User.new(user_params)
    puts "putting user:", @user
		if @user.save
			session[:user_id] = @user.id
			
      # redirect_to 'auth/fitbit'
			redirect_to '/auth/fitbit'
		else
			flash[:errors] = @user.errors.full_messages
			redirect_to '/register'
		end
  end

  def register
  	
  end

  def login

  end

  def user_params
  	params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/fitbit_auth_helper.rb
module FitbitAuthHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<div class="centerize">

<% if flash.notice %>
	<p class='notice'> <%= flash.notice %> </p>
<% end %>

<h3 class='aniron'>Days since leaving the shire: <%= @distance[1]["activities-tracker-distance"].count %> </h3>
<% @sum = 0 %>
<% @distance[1]["activities-tracker-distance"].each do |p| %>
<% @sum += p["value"].to_f %>
<% end %>
<h3 class='aniron'>Total Distance Travelled: <%= @sum.round(2) %>  </h3>


<table class="gondor title_text">
	<thead>
		<th>Day</th>
		<th>Steps</th>
		<th>Distance <br> Travelled</th>
		<th>Elevation <br> Gained</th>
		<th>Calories <br> Burnt</th>
		<th>Minutes <br> Asleep</th>
	</thead>
		<% count = 0 %>
		<% @distance[0]["activities-tracker-steps"].each do |p| %>
	<tr>
		<td> <%= p["dateTime"] %> </td>
		<td> <%= p["value"]%> </td>
		<td> <%= @distance[1]["activities-tracker-distance"][count]["value"].to_f.round(2)%> </td>
		<td> <%= @distance[2]["activities-tracker-elevation"][count]["value"] %> </td>
		<td> <%= @distance[3]["activities-tracker-calories"][count]["value"] %> </td>
		<td> <%= @distance[4]["sleep-minutesAsleep"][count]["value"] %> </td>
		<% count+=1 %>
	</tr>
		<% end %>
		
</table>

<p class='aniron'>Last checkpoint: <a class='aniron' href="/lands/rivendell">Rivendell</a></p>

</div>

app/views/fitbit_auth/index.html.erb
<%= link_to "Fitbit Sign In", auth_fitbit_path %>

app/views/lands/rivendell.html.erb
<div id="title" class="slide header">
  <h1 class="title_text">Rivendell</h1>
</div>

<div id="slide1" class="slide">
  <div class="title">
    <h1 class="aniron">Lore</h1>
    <p class="aniron">Rivendell was established by Elrond in the Second Age of Middle-earth in SA 1697. During the War of the Elves and Sauron, Eregion was laid waste and Elrond brought the survivors to Rivendell, soon Sauron laid siege to it but was eventually beaten back. Following the establishment of the Last Alliance of Elves and Men the hosts of Gil-galad and Elendil march to Imladris and laid camp in there to prepare their arms and then proceeded southeast to Dagorlad.</p>
  </div>
</div>

<div id="slide2" class="slide">
  <div class="title">
    <h1>Friends who have passed this way</h1>
    <ul>
      <li>Connor</li>
      <li>Michael -- recently</li>
      <li>Rovshen -- 21 days ago</li>
    </ul>
  </div>
  <img src="Rivendell1.jpg">
  <img src="Rivendell1.jpg"> 
</div>

<div id="slide3" class="slide">
  <div class="title">
    <h1>Other travellers</h1>
    <p>Lorem ipsum dolor sit amet, in velit iudico mandamus sit, persius dolorum in per, postulant mnesarchum cu nam. Malis movet ornatus id vim, feugait detracto est ea, eam eruditi conceptam in. Ne sit explicari interesset. Labores perpetua cum at. Id viris docendi denique vim.</p>
  </div>
</div>

<div id="slide4" class="slide header">
    <h1>Onward</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyWalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id = "navigation">
	<ul>
		<li>
			<a href="/users/login">login</a> |
		</li>
		<li>
			<a href="/dashboards/index">Map</a> |
		</li>
		<li>
			<a href="/register">register</a> |
		</li>
		<li class="pull-right">
			<a href="/sessions/destroy">logout</a>
		</li>
	</ul>
	<!-- <ul class="pull-right">
		
	</ul> -->
</nav>
<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/login.html.erb
<!DOCTYPE html>



<div id="frodo" style="margin:auto; margin-top:15px"></div>
<div class="centerize">
	<div class="row">
		<p>
			<% if flash["error"] %>
	 			<div class="errors"><%= flash["error"] %></div>
			<% end %>
		</p>
	</div>

	
	<%= form_for :user, :url => '/sessions/create' do |f| %>
		<%= f.label :email %>
		<%= f.text_field :email, required:true, :class => 'heroic_input' %>

		<%= f.label :password %>
		<%= f.password_field :password, required:true, :class => 'heroic_input' %>

		<%= f.button :Embark %>	
			
	<% end %>

app/views/users/register.html.erb
<!DOCTYPE html>
<div id="frodo" style="margin:auto; margin-top:15px"></div>

<div class="centerize">

	<div class="row">
		
			<% if flash["errors"] %>
		<% flash["errors"].each do |error_message| %> <br>
		 	<div class="errors"><%= error_message %></div>
			<% end %>
		<% end %>

			<% if flash.notice %>
				<p class='notice'> <%= flash.notice %> </p>
			<% end %>

	</div>
	
		<%= form_for :user, :url => '/users/create' do |f| %>
		<div class="row">
				<%= f.label :email, required:false %>
				<%= f.text_field :email, required:false, :class => 'heroic_input' %>
		</div>
		<div class="row">
			<div class="col-3">
				<%= f.label :password %>
				<%= f.password_field :password, :class => 'less heroic_input' %>
			</div>
			<div class="col-3">
				<%= f.label :Confirm %>
				<%= f.password_field :password_confirmation, :class => 'less heroic_input' %>
			</div>
				<%= f.button :Embark %>
		<!-- </div> -->

		<% end %>
	</div>
</div>